// @ts-nocheck -- skip type checking
import * as d_docs_5 from "../content/docs/india/indian-states-api.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/india/indian-railway-station.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/india/indian-cities-api.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/countries/countries-flag.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/countries/contry-dial-code.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/index.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: d_docs_0 }, { info: {"path":"countries/contry-dial-code.mdx","fullPath":"content/docs/countries/contry-dial-code.mdx"}, data: d_docs_1 }, { info: {"path":"countries/countries-flag.mdx","fullPath":"content/docs/countries/countries-flag.mdx"}, data: d_docs_2 }, { info: {"path":"india/indian-cities-api.mdx","fullPath":"content/docs/india/indian-cities-api.mdx"}, data: d_docs_3 }, { info: {"path":"india/indian-railway-station.mdx","fullPath":"content/docs/india/indian-railway-station.mdx"}, data: d_docs_4 }, { info: {"path":"india/indian-states-api.mdx","fullPath":"content/docs/india/indian-states-api.mdx"}, data: d_docs_5 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"Documentation","pages":["index","countries","india"],"description":"JSONly API Documentation","root":true,"icon":"BookOpen"}}, {"info":{"path":"countries/meta.json","fullPath":"content/docs/countries/meta.json"},"data":{"title":"Global Data","pages":["countries-flag","contry-dial-code"],"icon":"Globe"}}, {"info":{"path":"india/meta.json","fullPath":"content/docs/india/meta.json"},"data":{"title":"Indian Datasets","pages":["indian-cities-api","indian-states-api","indian-railway-station"],"icon":"Map"}}])